# Generated by Django 3.0.2 on 2020-01-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mata_description',
            new_name='meta_description',
        ),
    ]
